### PR TITLE
Make `Either` example into real Haskell

### PR DESCRIPTION
**Pull request by fosskers**
I'm almost done the chapter - maybe hold off merging until I get to the end?

### CODE REVIEW

**Comment by hmemcpy** [comment]
Sure, no worries, take your time!

**Comment by fosskers** [comment]
Should be good to go!

**Comment by fosskers** [comment]
Examples in later chapters occasionally use this same pseudo-syntax. Here's one from Chapter 6:

```haskell
List a = Nil | Cons a (List a)
```
which is fine, because at this location in particular he's talking about the "algebraness" of ADTs and immediately compares it to:

```
x = 1 + a * x
```

 In the `Either` example in this PR, I still think it makes sense to add `data`, since in the line above he says "Here's how it's defined in Prelude".

**Comment by hmemcpy** [comment]
Sorry for the delays.
I'll merge it, as there exist other definitions that do include the `data` keyword before. Thanks for the PR!

**Pull request merged**
