### PR TITLE
Update 1.3's C++ concept implementation of Monoid

### PR DESCRIPTION
**Pull request by alfonsoros88**

### CODE REVIEW

**Comment by hmemcpy** [comment]
Will gonna need a ruling here. @BartoszMilewski, WDYT?

**Comment by BartoszMilewski** [comment]
Looks good. I haven't been following C++. Is there a compiler that could type check this code?

**Comment by alfonsoros88** [comment]
Hi :) I could compile with the latest gcc. The only feature that is still not yet supported by gcc is the constexpr std::string. But it is in the C++20 standard so hopefully it will be supported soon enough.

**Comment by BartoszMilewski** [comment]
I asked my friend Eric Niebler for comments. This is what he said.

\begin{snip}{cpp}
template<class T>
struct mempty : std::false_type {};

>   I would probably just forward-declare this but leave the primary template undefined.


template<class T>
using mempty_v = mempty<T>::value;

> Probably you don't want to use a class static here. Not all types have a constexpr default constructor, and you don't want to introduce order-of-initialization issues. Maybe a static member function named value() that returns the empty value.


template<class T>
T mappend(T, T) = delete;

template<class M>
concept Monoid = requires (M m) {
    { mempty_v<M> } -> std::convertible_to<M>;

>   If you went with a static member function, this would be:

  { mempty<M>::value() } -> std::convertible_to<M>;

>   And see below about "same_as".

 
    { mappend(m, m) } -> std::convertible_to<M>;
};

>   I would strengthen "convertible_to" to "same_as". There's no reason not to turn the screws down tightly here.

**Comment by hmemcpy** [comment]
So what's the verdict? Can I merge this? :)

**Comment by BartoszMilewski** [comment]
If we can incorporate Eric's comments, then yes.

**Comment by alfonsoros88** [comment]
> If we can incorporate Eric's comments, then yes.

I'd incorporate them some days ago, just have a look :)

**Comment by BartoszMilewski** [comment]
Cool! Thanks!

**Pull request merged**
