### PR TITLE
Fix minor typos

### PR DESCRIPTION
**Pull request by ktgw0316**

### CODE REVIEW

**Comment by ktgw0316** [comment]
I edited the LaTeX files with VS Code, and its formatter also removed white spaces at end of each line.

**Comment by drupol** [comment]
Hey hi !

Thanks for your contribution.

I tried to build your branch locally, but I got this issue:

```
 !  ~/C/h/milewski-ctfp-pdf   ktgw0316/master  nix build .#ctfp                                                                                                                                                              nixpkgs#gh 
error: builder for '/nix/store/325f03z2m1x12y5jlfs7xrb0lbdfnfs0-ctfp-f6d981f.drv' failed with exit code 12;
       last 25 log lines:
       > 9.pygtex)) [383]
       > Chapter 26.
       > (./content/3.10/ends-and-coends.tex
       >
       > ! LaTeX Error: \symbfallowed only in math mode.
       >
       > See the LaTeX manual or LaTeX Companion for explanation.
       > Type  H <return>  for immediate help.
       >  ...
       >
       > l.18 different categories \cat
       >                               {C} and \cat{D}. A functor, which describes
       > Output written on ctfp.pdf (392 pages).
       > Transcript written on ctfp.log.
       > Latexmk: Examining 'ctfp.log'
       > === TeX engine is 'XeTeX'
       > Latexmk: Index file 'ctfp.idx' was written
       > Latexmk: References changed.
       > Latexmk: Log file says output to 'ctfp.pdf'
       > Latexmk: Errors, so I did not complete making targets
       > Collected error summary (may duplicate other messages):
       >   pdflatex: Command for 'pdflatex' gave return code 1
       >       Refer to 'ctfp.log' for details
       > Latexmk: Use the -f option to force complete processing,
       >  unless error was exceeding maximum runs, or warnings treated as errors.
       For full logs, run 'nix log /nix/store/325f03z2m1x12y5jlfs7xrb0lbdfnfs0-ctfp-f6d981f.drv'.
```

Can you let me know if you had the same issue locally?

**Comment by ktgw0316** [comment]
@drupol Sorry, I pushed a commit to fix the issue, and now I can build the branch without error.

**Review by drupol — APPROVED** [review]
All good here, thanks for your contribution !

**Pull request merged**
