### PR TITLE
Make spaces after functors consistent

### PR DESCRIPTION
**Pull request by EFanZh**
I found that when applying a functor, the usages of spaces are inconsistent. Some are like `F f`, while others would add an explicit space like `F\ f`. Now I am not sure which one is more correct. I am choosing the first one because it seems to have more usages.

### CODE REVIEW

**Review by drupol — APPROVED** [review]
Thanks!

**Comment by drupol** [comment]
Could you please rebase ?

**Comment by EFanZh** [comment]
Done.

**Comment by drupol** [comment]
Thanks again !

**Pull request merged**
