### PR TITLE
Switch to using Nix flakes

### PR DESCRIPTION
**Pull request by aszlig**
Someone has requested me to build this book, since they didn't have Nix.

So when looking at the Nix expressions I found that there was only a `shell.nix` and the `default.nix` was essentially just aliasing the `shell.nix` but without the pinning.

However, with Nix flakes we no longer need to do pinning like this and we instead have a `flake.lock` file, which essentially pins the corresponding revisions.

I also added a `default.nix`, which uses `flake-compat` to make sure that nix-shell and nix-build work as before.

Since so far the way to build the PDF(s) was to get into a Nix shell and run make accordingly. For me however it's unacceptable to build random code without the Nix sandbox, so while writing a proper `default.nix` I decided it would be better to turn it into a Nix flake.

Apart from the previous ways to build this project we now have:

```sh-session
$ nix develop # To get a Nix shell (similar to nix-shell but cached)
$ nix build # The default edition
$ nix build .\#ctfp-scala # The Scala edition
$ nix build .\#ctfp-ocaml # The OCaml edition
```

### CODE REVIEW

**Comment by hmemcpy** [comment]
Oh wow, this is fantastic! I'll admit I haven't really touched the Nix build every since I first attempted to hack it together.... I wasn't even sure it was still building!

Thanks very much!!

**Comment by aszlig** [comment]
@hmemcpy: Holy cow, that was quick, thanks! Btw. another advantage is that now the book can be built by simply issuing:

```sh-session
$ nix build github:hmemcpy/milewski-ctfp-pdf
```

**Comment by hmemcpy** [comment]
😮 

This is amazing, really :) Thank you for the PR!

**Comment by drupol** [comment]
I'm wondering if we could do that in Github actions as well :-)

**Comment by aszlig** [comment]
@drupol: You mean using something like https://github.com/marketplace/actions/install-nix?

**Comment by drupol** [comment]
> @drupol: You mean using something like https://github.com/marketplace/actions/install-nix? If yes I could give it a try, although I'm no expert if it comes to GitHub actions.

Yeah something like that. I would be nice to see if it's better to use nix within Github actions to build the PDFs.

TBH, I don't think we should change something and having both system is perfectly fine!

**Pull request merged**
