### PR TITLE
Corrected occasional misspelling of Lawvere and other minor spelling mistakes, and capitalized Cartesian

### PR DESCRIPTION
**Pull request by george-hawkins**
I made some minor spelling corrections.

Note: unfortunately my editor feels that every line, including the last one, should end with a newline character so the last line of each file I changed also shows as changed in the diffs.

I did also start correcting "cartesian" (spelled with a small "c") to "Cartesian" but then decided to leave this alone. Using a capital "C" however does seem to be the norm, e.g. if you look at [Cartesian product on Wikipedia](https://en.wikipedia.org/wiki/Cartesian_product) or on [Wolfram](http://mathworld.wolfram.com/CartesianProduct.html).

### CODE REVIEW

**Comment by hmemcpy** [comment]
Amazing! Thanks so much for this!
I think you're right to convert Cartesian to capital. If you can, please add another commit, and I will merge it!

**Comment by george-hawkins** [comment]
As requested - added a commit to change all occurrences of cartesian to Cartesian, but left bicartesian as it is - this seems to be the standard convention.

**Comment by hmemcpy** [comment]
Hmm, I'm so sorry to say this, but I just checked the [Product (category theory)](https://en.wikipedia.org/wiki/Product_(category_theory)) page on wikipedia, and it seems to define everything in lowercase... I really have no idea :)

**Comment by hmemcpy** [comment]
They are really inconsistent about this too, other pages seem to capitalize Caresian.

**Comment by george-hawkins** [comment]
Hmm... tough call but Wolfram and various others go for the capital 😄

**Comment by hmemcpy** [comment]
Then sure! IF there's an issue - we can always revert :)
I'll merge this. Thanks again for the help!

**Comment by george-hawkins** [comment]
The OED also goes for caps but I'll leave it up to you 😄

**Pull request merged**
