### PR TITLE
refactor: CI and nix

### PR DESCRIPTION
**Pull request by drupol**
Hi,

The motivation of this PR is reproducibility and accessibility. I want to make sure that anyone will be able to build the PDFs using the same mechanism and workflow and that everyone will use the same version of dependencies to better track potential issues.

I've been working with Nix and LaTeX at work and for personal stuff lately and I'm now ready to upgrade this project with the best practices and technologies. The idea here is to make sure we don't break the build system based on Nix and provide a better development environment for contributors.

Status:

- [x] Update README ([view it here](https://github.com/hmemcpy/milewski-ctfp-pdf/tree/refactor-ci-and-nix))
- [x] Update Nix stack  
  - [x] Switch from `numtide/flake-utils` to `flake-parts`
  - [x] Reformat Nix files using `alejandra`
  - [x] Switch from `nixos-21.11` to `nixpkgs-unstable`, from `python-3.8` to `python-3.11`
  - [x] Add `.envrc` to load the development environment instantly
- [x] Update Github workflows
  - [x] Disable the making of a pre-release at each commit but merely at each tag (eco programming)
  - [x] Trigger checks and builds of each document flavors at each PR so we don't have to test manually if a build succeed (reference to https://github.com/hmemcpy/milewski-ctfp-pdf/pull/304)
  - [x] Check repository files with `prettier` at each pull-request 
- [x] Automatic reformatting of files using `prettier`
- [x] Remove obsolete files from the repo, remove of all custom font files since they are available in Texlive and Nix
- [x] Lint LaTeX files using `latexindent.pl` 

Collateral things:
- A bug in `minted` LaTeX package has been encountered, see https://github.com/gpoore/minted/issues/353, a workaround(https://github.com/hmemcpy/milewski-ctfp-pdf/pull/306/commits/91779a5d1c3ac4f52e19dd4f1165fe0f4f2f8d95) has been put in place and it's working.
- Add `pygments-style-github` in `nixpkgs`, see https://github.com/NixOS/nixpkgs/pull/214015

### CODE REVIEW

**Comment by hmemcpy** [comment]
I really appreciate the hard work you're putting in this <3

**Comment by drupol** [comment]
Thanks mate, it's been a while I wanted to do that... but I was lacking knowledge in LaTeX and Nix... and I think now it is the time :)
I'll finish this today after work.

**Comment by hmemcpy** [comment]
Awesome, because I haven't touched this stuff in years :) Go for it!

**Comment by hmemcpy** [comment]
Please make sure all those indentations now in code snippets do not render as extra whitespace.

**Comment by drupol** [comment]
> Please make sure all those indentations now in code snippets do not render as extra whitespace.

There is a configuration file `.latexindent.yaml` which prevent the verbatim environment to be modified. So it's all good.

**Comment by hmemcpy** [comment]
<3

**Comment by drupol** [comment]
I think this PR is ready, let me know if you're ok with it :)

**Comment by drupol** [comment]
I know it's a lot to review.

That said, I tried to be very cautious and tidy with commits.

The easiest way to review such PR is to click on each commit and understand what it's doing.

Let me know if something needs to be changed.

**Review by hmemcpy — APPROVED** [review]
Awesome work, mate! I would never do this myself in a million years, so I appreciate the effort :)

**Pull request merged**
