### PR TITLE
Added chapters 2.1 and 2.2

### PR DESCRIPTION
**Pull request by raol**

### CODE REVIEW

**Comment by hmemcpy** [comment]
Great job! I appreciate you converting things to formulas :)
If you don't mind, I'd like to tweak a few things so they are more consistent with the rest. Will make it easier to replace later.

**Comment by raol** [comment]
Sure. Do all changes you need.

Regarding formulas, I don't know how to make it right. Because some parts are written as math like _C_ and so on and some as code `Lim D`. And it makes really hard to come up with pretty and consistent design.

**Comment by hmemcpy** [comment]
Yeah... I'm not sure that I want it too "mathy", maybe leave it as-is (i.e., with monospaced font, using `\code`), although that `\Delta_c` is damn nice :)
We'll see... I want to get all the chapters done first, and then the improvements.

**Comment by hmemcpy** [comment]
Fixed via #44 :)

**Comment by hmemcpy** [comment]
Sorry, I goofed, and ended up creating a separate PR for this...

**Pull request closed without merging**
