### PR TITLE
Switch GitHub Actions workflow to use Nix

### PR DESCRIPTION
**Pull request by aszlig**
This is a catch-up on https://github.com/hmemcpy/milewski-ctfp-pdf/pull/253#issuecomment-687111430:

> I'm wondering if we could do that in Github actions as well :-)

Right now there are the following issues left to solve:

  * [ ] Cache NARs of the direct build dependencies (see https://github.com/NixOS/nix/issues/1245)
  * [ ] Make sure the artifacts get a proper MIME type (application/pdf)
  * [ ] Fix generating (pre-)releases

The first item is the reason why the build is slower than the existing workflow because the TeX Live environment needs to be built all over again, so until we have a good way to solve this (maybe even use the [Cachix Action](https://github.com/marketplace/actions/cachix)?) it's probably not worth pursuing this further.

Cc: @drupol, @hmemcpy

### CODE REVIEW

**Comment by aszlig** [comment]
Since I've listed the disadvantages in the pull request text already, I'll answer on:

> 3. What would be the advantages of switching to such a system?

Essentially it would be to consolidate build methods, so far we have a Makefile, some custom GitHub Action using `latexmk` and which is a bit harder to reproduce locally and the packages in `flake.nix`. This essentially would switch everything to `flake.nix` so that for example if you want to add more editions/variants you only have *one* file to change.

Another advantage is that the build is reproducible, no matter whether it's with GH Actions or locally.

**Comment by aszlig** [comment]
@drupol: Since you did the GH Action implementation so far: How did you manage to get build artifacts to use the right MIME type?

**Comment by drupol** [comment]
> Another advantage is that the build is reproducible, no matter whether it's with GH Actions or locally.

Fair enough, that's a rather good argument :-)

**Comment by drupol** [comment]
> @drupol: Since you did the GH Action implementation so far: How did you manage to get build artifacts to use the right MIME type?

I didn't do anything special, it worked out of the box.

**Comment by drupol** [comment]
Just FYI, I'm working on an updated Github Action workfile using Nix exclusively. It's almost done: https://github.com/drupol/milewski-ctfp-pdf/runs/5334870499

**Comment by drupol** [comment]
PR Done: https://github.com/hmemcpy/milewski-ctfp-pdf/pull/286

**Comment by drupol** [comment]
I think we can close this now, please reopen if needed.

**Pull request closed without merging**
