### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by marulitua**
Based on [this](https://github.com/hmemcpy/milewski-ctfp-pdf/issues/58) issue
I also need to add `-interaction=nonstopmode` option to able to make it work
Please change the api key before you use it

### CODE REVIEW

**Comment by hmemcpy** [comment]
This is absolutely incredible, thank you! Let me try it out, and I'll happily merge it in!

**Comment by hmemcpy** [comment]
Looks great! Thank you for your hard work. I'm pulling the PR locally to make some changes, and add your name to the contributors list in README :)
Can you please reply with the proper way you'd like your name spelled?

Thanks again!

**Comment by hmemcpy** [comment]
Oooops, I'm sorry, I made a mistake! I somehow accidentally pushed my squashed rebase to YOUR fork, and it caused your PR changes to disappear :(
Very sorry about this, I really want you to have a "Contributor" badge! Perhaps you could force-push your local changes again to master and send a new PR?

**Comment by marulitua** [comment]
Ok, no problem

**Pull request closed without merging**
